/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SwingUtilsTestWindow.java
 *
 * Created on Nov 24, 2011, 1:24:17 PM
 */
package pl.rzarajczyk.breaktime.utils;

import java.awt.Color;

/**
 *
 * @author rafalz
 */
public class SwingUtilsTestWindow extends ExtendedJFrame {

    /** Creates new form SwingUtilsTestWindow */
    public SwingUtilsTestWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testsInProgressLabel = new javax.swing.JLabel();
        waitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tests in progress...");

        testsInProgressLabel.setText("Tests in progess - the screen may behave strange.");

        waitLabel.setText("Please wait patiently...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testsInProgressLabel)
                    .addComponent(waitLabel))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testsInProgressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitLabel)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel testsInProgressLabel;
    private javax.swing.JLabel waitLabel;
    // End of variables declaration//GEN-END:variables
}
