package pl.rzarajczyk.utils.system.notification;

interface NotificationWithSupportedMarker extends Notification {
    
    /**
     * Checks if this class supports the current platform (which means the
     * notification generated by this class will appear on the screen)
     * @return true if the current platform is supported by this class
     */
    boolean isSupported();
    
}
