name: Build and Publish

on:
  push:
    branches:
     - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - run: mkdir staging-jar && cp target/*.jar staging-jar
      - uses: actions/upload-artifact@v4
        with:
          name: break-time.jar.zip
          path: staging-jar
          retention-days: 90
      - run: mkdir staging-exe && cp target/*.exe staging-exe
      - uses: actions/upload-artifact@v4
        with:
          name: break-time.exe.zip
          path: staging-exe
          retention-days: 90